# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  cli-zig:
    desc: Run Zig cli orchestration
    dir: ./cli-zig
    cmds:
      - zig build run -- --name lifesat --path ../data/lifesat.csv --columns lifesat,age,gender,income,social_trust,discrimination_index,work_stress,religiosity,social_activity,economic_satisfaction,wellbeing --target lifesat

  analyzer:
    desc: Run Python analysis and ML model
    dir: ./analyzer
    cmds:
      - python3 main.py --name lifesat --path lifesat.csv --columns col1,col2,col3 --target lifesat

  backend:
    desc: Run GO backend
    cmds:
      - go run main.go

  frontend:
    desc: Run JS frontend
    cmds:
      - npm run dev
